# Oracle DB Connection
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=sQjLQyIIiLlTLbZztCAkkozOSizxJRIV

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


razorpay.api.key=rzp_live_T1DcDXtaQqDc4T
razorpay.api.secret=vhQVEpi5bhujcv2wGGpg5A5e


#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=hukmil.lane.raja@gmail.com
#spring.mail.password=uwkvqusciqbpitqb
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp-relay.brevo.com
#spring.mail.port=587
spring.mail.username=aeaab4001@smtp-brevo.com
spring.mail.password=mM0nb6UJB3xakhTN
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

email.sender-email=hukmil.lane.raja@gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000


logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
logging.level.jakarta.mail=DEBUG


spring.mail.properties.mail.debug=true